# Generated by Django 4.0.5 on 2022-08-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CA', 'Cart'), ('OR', 'Order'), ('WI', 'Wishlist')], default='CA', max_length=10),
        ),
    ]
