# Generated by Django 4.0.5 on 2022-08-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_remove_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='address',
        ),
    ]
