# Generated by Django 4.0.5 on 2022-08-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_user_order_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='user',
        ),
    ]
